all:

clean:

PROG=benchmark.py
test:
	./$(PROG)
	@(./$(PROG);./$(PROG);./$(PROG);./$(PROG);./$(PROG);  ./$(PROG);./$(PROG);./$(PROG);./$(PROG);./$(PROG) )|../avgcalc.py

PROG2=python3 benchmark.py
test2:
	$(PROG2)
	@($(PROG2);$(PROG2);$(PROG2);$(PROG2);$(PROG2);  $(PROG2);$(PROG2);$(PROG2);$(PROG2);$(PROG2) )|../avgcalc.py
