name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-with-msbuild:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.100-rc.1.23463.5'
    - name: Restore dependencies
      working-directory: C#
      run: dotnet restore fft-benchmark.csproj
    - name: Build
      working-directory: C#
      run: dotnet build --no-restore fft-benchmark.csproj

  build-with-make:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.100-preview.6.23330.14'
    - name: Build
      working-directory: C#
      run: make

  package-deb:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.100-preview.6.23330.14'
    - name: Build
      working-directory: C#
      run: make
    - name: Create a package
      working-directory: C#
      run: make package
    - name: Publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: fft-benchmark
        path: C#/*.deb
        retention-days: 3
